### ISSUE TITLE
The Server receives data after stoped

### ISSUE THREAD

**Issue by hakikpaci** [jchristn/SuperSimpleTcp#121] opened 2022-02-19 08:53 UTC
Hello,

On new version v2.6.0.1, the server receives data after the server stopped as bellow (maybe it must work like that) :

Listener IP   : [127.0.0.1]
Listener Port : [9000]
Use SSL       : [y/N]? N
Server started
Command [? for help]: [SimpleTcp.Server] starting data receiver for: 127.0.0.1:58177
[127.0.0.1:58177] client connected
[SimpleTcp.Server] data receiver started for client 127.0.0.1:58177
[127.0.0.1:58177]: test

Command [? for help]: stop
[SimpleTcp.Server] stopped listening
[SimpleTcp.Server] stopped
Command [? for help]: [127.0.0.1:58177]: Hello!
[127.0.0.1:58177]: Test

Also on the client-side when I try to execute the disconnect command  ( ClientTest sample) it hangs on  as below : 

Server IP   : [127.0.0.1]
Server Port : [9000]
Use SSL     : [y/N]? N
[SimpleTcp.Client] initializing client
[SimpleTcp.Client] connecting to 127.0.0.1:9000
[SimpleTcp.Client] attempting connection to 127.0.0.1:9000
[SimpleTcp.Client] connected to 127.0.0.1:9000
*** Server 127.0.0.1:9000 connected
Command [? for help]: send
Data: [Hello!] test
Command [? for help]: send
Data: [Hello!]
Command [? for help]: send
Data: [Hello!] Test
Command [? for help]: [127.0.0.1:9000] Test

Command [? for help]: disconnect
**[SimpleTcp.Client] disconnecting from 127.0.0.1:9000**

**Comment by jchristn** [comment] 2022-02-19 15:00
Hi, stopping the server does not tear down existing connections; it only prevents new connections from being accepted.  So the behavior you experience is correct, you can still send the server data after stopping the server.

What framework/runtime and operating system are you using?  I'm not experiencing the hang on disconnect issue using the ClientTest and ServerTest project.

**Comment by jchristn** [comment] 2022-02-19 17:47
I just tested again and the only issue I could find was an uncaught ```AggregateException``` when running .NET Core 3.1 or above in the client ```DataReceiver``` but it wasn't affecting operation.  I updated the library to v2.6.0.3 to address that, however, I have been unable to reproduce the issue with hanging on disconnect.  

Please let me know what operating system and framework/runtime you are using and if possible please provide sample code to reproduce.  Cheers

**Comment by hakikpaci** [comment] 2022-02-19 18:13
I compiled on VS 2019 and .Net framework 4.8 on windows 10, 64 bit Pro version.

On my tests I did not change anything on your code.


I will do some more tests and I will come back.

Regards

**Comment by jchristn** [comment] 2022-02-19 19:05
Just tested on 4.8 and it worked on my end.  You may notice up to one second in delay between ```disconnecting``` and ```disconnected``` as I had to modify the internal ```DataReadAsync``` since ```Stream.ReadAsync``` doesn't obey ```CancellationTokenSource``` cancellation.

![image](https://user-images.githubusercontent.com/1421081/154815209-d0058a92-9e77-4921-bd2c-7fb8d52b436a.png)

**Comment by hakikpaci** [comment] 2022-02-20 08:29
Hi Joel,

I did some test on different .net versions and on the version v2.6.0.1 it hangs on my PC.
![SSTCP_test1](https://user-images.githubusercontent.com/6296371/154834644-ee472763-b5d2-4369-aed2-9f55482976b7.jpg)


After downloading the new version 2.6.0.3 I do not face the same problem again but I thing there is a new issue, the client on .net 4.8, 4.6.1 and .net core 3.1 do not receives the data from server.

![SSTCP_test2](https://user-images.githubusercontent.com/6296371/154834723-bbd3c151-7b86-4fde-a96a-5b8af1824419.jpg)
![SSTCP_test3](https://user-images.githubusercontent.com/6296371/154834728-7bae19dd-88ea-44db-9009-ee3277060029.jpg)


Regards

**Comment by hakikpaci** [comment] 2022-02-20 08:30
On .Net 5.0 it works

**Comment by jchristn** [comment] 2022-02-20 18:55
Hi @hakikpaci I have a fix, but I've asked @tinohager to weigh in with an opinion as well.  Please refer to https://github.com/jchristn/SuperSimpleTcp/issues/123 - closing this one out since it's a duplicate.  Thanks!

**Comment by jchristn** [comment] 2022-02-20 18:55
Also please revert to 2.6.0.1

**Closed by jchristn** 2022-02-20 18:55 UTC
