### ISSUE TITLE
SimpleTcpClient no longer works after update to version 2.6.0.1 - 2.6.0.3

### ISSUE THREAD

**Issue by tinohager** [jchristn/SuperSimpleTcp#123] opened 2022-02-19 21:21 UTC
No data are received on the event

**Comment by tinohager** [comment] 2022-02-19 21:58
![image](https://user-images.githubusercontent.com/8215186/154820487-ec3e6ef4-8b9a-4bd0-b084-e4bdaee180cf.png)

**Comment by jchristn** [comment] 2022-02-19 22:10
Hi @tinohager which OS and framework/runtime were you using?  I tested .NET Framework, .NET Core, and .NET 5 and 6, and had no issue.  Could you help me reproduce?

**Comment by jchristn** [comment] 2022-02-19 22:14
Cancel that, looks like you're referring to server to client communication.  I just tested all versions client to server.  Looking into it now.

**Comment by tinohager** [comment] 2022-02-19 22:16
Windows 10/64bit in my unit test i have optimize the test case `Start_StartServerAndConnectWithOneClientAndSendMessages_Successful`

**Comment by tinohager** [comment] 2022-02-19 22:17
![image](https://user-images.githubusercontent.com/8215186/154820896-de7c3315-5cc9-46aa-8599-b9309860ad6b.png)

**Comment by jchristn** [comment] 2022-02-19 22:23
Thanks, my patch in 2.6.0.2 broke it trying to resolve another issue.  I've unlisted 2.6.0.2+ from NuGet and will work on resolving this.  Thanks for letting me know.  ```NetworkStream.ReadAsync``` doesn't actually use ```CancellationToken```s that are passed into them which caused me to have to do some strange gymnastics with tasks.  I will do my best to get to it this weekend.  Thanks for letting me know.

**Comment by tinohager** [comment] 2022-02-19 22:33
https://github.com/dotnet/runtime/issues/24093

**Comment by jchristn** [comment] 2022-02-19 22:50
Exactly 😊

**Comment by jchristn** [comment] 2022-02-20 02:48
@tinohager I'd love to get your opinion on how to address this.  The easiest way, in the client ```DataReadAsync```, is to use synchronous ```.Read``` calls against the stream, having set the ```_networkStream.ReadTimeout``` to ```_settings.ReadTimeoutMs``` and the same for ```_sslStream```.  That parameter ```Stream.ReadTimeout``` is not considered when using ```.ReadAsync```.

I'm still looking for a solution that leverages ```async```.  

Here's what I've come up with for sync:
```
        private async Task<byte[]> DataReadAsync(CancellationToken token)
        {  
            byte[] buffer = new byte[_settings.StreamBufferSize];
            int read = 0;

            try
            {
                if (!_ssl)
                {
                    read = _networkStream.Read(buffer, 0, buffer.Length);
                }
                else
                {
                    read = _sslStream.Read(buffer, 0, buffer.Length);
                }

                if (read > 0)
                {
                    using (MemoryStream ms = new MemoryStream())
                    {
                        ms.Write(buffer, 0, read);
                        return ms.ToArray();
                    }
                }
                else
                {
                    throw new SocketException();
                }
            }
            catch (IOException)
            {
                // thrown if ReadTimeout (ms) is exceeded
                // see https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream.readtimeout?view=net-6.0
                // and https://github.com/dotnet/runtime/issues/24093
                return null;
            }
        }
```
And beforehand, setting the ```_networkStream.ReadTimeout``` and ```_sslStream.ReadTimeout``` in both ```Connect()``` and ```ConnectWithRetries```.

Doing this synchronously is not optimal but it does work (quite well).  Would you happen to have a suggestion?  Or if this is sufficient, I'll put together a new version and publish.  Cheers, Joel

**Comment by tinohager** [comment] 2022-02-20 19:53
```cs
using System;
using System.IO;
using System.Net.Sockets;
using System.Threading;
using System.Threading.Tasks;

class TestClient : IDisposable
{
    private readonly TcpClient _tcpClient;
    private readonly Stream _stream;
    private CancellationTokenSource _cancellationTokenSource;

    public TestClient()
    {
        this._cancellationTokenSource = new CancellationTokenSource();
        this._tcpClient = new TcpClient();

        _ = Task.Run(async () => await this.DataReceiver(this._cancellationTokenSource.Token), this._cancellationTokenSource.Token);

        IAsyncResult ar = this._tcpClient.BeginConnect("127.0.0.1", 20007, null, null);
        WaitHandle wh = ar.AsyncWaitHandle;

        if (!ar.AsyncWaitHandle.WaitOne(TimeSpan.FromMilliseconds(1000), false))
        {
            this._tcpClient.Close();
            wh.Close();
            throw new TimeoutException($"Timeout connecting to");
        }

        this._tcpClient.EndConnect(ar);
        this._stream = this._tcpClient.GetStream();

        this._stream.WriteAsync(new byte[] { 0x06, 0x01 });
    }

    public void Dispose()
    {
        Console.WriteLine($"{nameof(Dispose)} - start...");

        this._cancellationTokenSource.Cancel();
        this._cancellationTokenSource.Dispose();

        this._stream.Close();
        this._stream.Dispose();

        if (this._tcpClient.Connected)
        {
            this._tcpClient.Close();
        }
        this._tcpClient.Dispose();

        Console.WriteLine($"{nameof(Dispose)} - done");
    }

    private async Task DataReceiver(CancellationToken cancellationToken = default)
    {
        while (!cancellationToken.IsCancellationRequested && this._tcpClient != null)
        {
            if (!this._tcpClient.Connected)
            {
                Console.WriteLine($"{nameof(DataReceiver)} - Client not connected");
                await Task.Delay(100).ConfigureAwait(false);
            }

            try
            {
                Console.WriteLine($"{nameof(DataReceiver)} - Wait for data...");
                using var timeoutCancellationToken = new CancellationTokenSource(100);
                using var linkedCancellationToken = CancellationTokenSource.CreateLinkedTokenSource(timeoutCancellationToken.Token, cancellationToken);

                await DataReadAsync(linkedCancellationToken.Token).ContinueWith(async task =>
                {
                    if (task.IsCanceled)
                    {
                        Console.WriteLine($"{nameof(DataReceiver)} - Timeout");
                        return;
                    }

                    byte[] data = task.Result;

                    if (data == null)
                    {
                        Console.WriteLine($"{nameof(DataReceiver)} - No data received");
                        await Task.Delay(100).ConfigureAwait(false);
                        //continue;
                    }

                    Console.WriteLine(BitConverter.ToString(data));

                }).ConfigureAwait(false);
            }
            catch (Exception exception)
            {
                Console.WriteLine($"{nameof(DataReceiver)} - {exception}");
                break;
            }
        }
    }

    private async Task<byte[]> DataReadAsync(CancellationToken cancellationToken)
    {
        byte[] buffer = new byte[100];

        var numberOfBytesToRead = await this._stream.ReadAsync(buffer, 0, buffer.Length, cancellationToken).ConfigureAwait(false);
        Console.WriteLine($"{nameof(DataReadAsync)} - NumberOfBytesToRead:{numberOfBytesToRead}");

        using (var memoryStream = new MemoryStream())
        {
            await memoryStream.WriteAsync(buffer, 0, numberOfBytesToRead, cancellationToken).ConfigureAwait(false);
            return memoryStream.ToArray();
        }
    }
}
```

**Comment by tinohager** [comment] 2022-02-20 19:55
The Timeout work with netcoreapp 3.0 and NET 6

**Comment by tinohager** [comment] 2022-02-20 19:59
I was looking for a test tool to simulate certain cases but didn't find anything optimal right away. What do you use?

**Comment by tinohager** [comment] 2022-02-20 20:40
with .net 4.8 DataReadAsync is not stopped on cancellationToken

What exactly is the requirement here? Do you want the client to just stop properly or do you want to start reading over and over again?

**Comment by jchristn** [comment] 2022-02-20 21:11
Hi @tinohager the issue is that if you call ```Disconnect``` on the client, it has to terminate the ```DataReceiver``` which needs to cancel the ```stream.ReadAsync``` in ```DataReadAsync```.  The original issue was that calling ```Disconnect``` followed by ```Connect``` from the client wouldn't work.

It appears I'll either have to a) use the sync solution I referenced above or b) put in preprocessor ```#if``` statements to have separate code for .NET Framework, .NET Core, .NET5/6.  

Do you have a preference?  Cheers and thanks for your input.

**Comment by tinohager** [comment] 2022-02-20 21:40
Can you check this logic?

```
using System;
using System.IO;
using System.Net.Sockets;
using System.Threading;
using System.Threading.Tasks;

class TestClient : IDisposable
{
    private TcpClient _tcpClient;
    private Stream _stream;
    private CancellationTokenSource _cancellationTokenSource;

    public TestClient()
    {
        this._cancellationTokenSource = new CancellationTokenSource();

        _ = Task.Run(async () => await this.DataReceiver(this._cancellationTokenSource.Token), this._cancellationTokenSource.Token);
    }

    public void Dispose()
    {
        Console.WriteLine($"{nameof(Dispose)} - start...");

        this._cancellationTokenSource.Cancel();
        this._cancellationTokenSource.Dispose();

        this._stream?.Close();
        this._stream?.Dispose();

        if (this._tcpClient != null)
        {
            if (this._tcpClient.Connected)
            {
                this._tcpClient.Close();
            }
            this._tcpClient.Dispose();
        }

        Console.WriteLine($"{nameof(Dispose)} - done");
    }

    public void Connect()
    {
        this._tcpClient = new TcpClient();

        IAsyncResult ar = this._tcpClient.BeginConnect("127.0.0.1", 20007, null, null);
        WaitHandle wh = ar.AsyncWaitHandle;

        if (!ar.AsyncWaitHandle.WaitOne(TimeSpan.FromMilliseconds(1000), false))
        {
            this._tcpClient.Close();
            wh.Close();
            throw new TimeoutException($"Timeout connecting to");
        }

        this._tcpClient.EndConnect(ar);
        this._stream = this._tcpClient.GetStream();
    }

    public void Disconnect()
    {
        this._stream?.Close();
        this._stream?.Dispose();
        this._tcpClient.Close();
        this._tcpClient.Dispose();
    }

    public async Task SendDataAsync()
    {
        await this._stream.WriteAsync(new byte[] { 0x06, 0x01 });
    }

    private async Task DataReceiver(CancellationToken cancellationToken = default)
    {
        while (!cancellationToken.IsCancellationRequested)
        {
            if (this._tcpClient == null)
            {
                Console.WriteLine($"{nameof(DataReceiver)} - TcpClient not initialized");
                await Task.Delay(100, cancellationToken).ContinueWith(task => { }).ConfigureAwait(false);
                continue;
            }

            if (!this._tcpClient.Connected)
            {
                Console.WriteLine($"{nameof(DataReceiver)} - Client not connected");
                await Task.Delay(100, cancellationToken).ContinueWith(task => { }).ConfigureAwait(false);
                continue;
            }

            if (this._stream == null)
            {
                Console.WriteLine($"{nameof(DataReceiver)} - Stream not ready");
                await Task.Delay(100, cancellationToken).ContinueWith(task => { }).ConfigureAwait(false);
                continue;
            }

            try
            {
                Console.WriteLine($"{nameof(DataReceiver)} - Wait for data...");

                await Task.Run(async () =>
                {
                    using (cancellationToken.Register(() => this._stream.Close()))
                    {
                        await DataReadAsync(cancellationToken).ContinueWith(async task =>
                        {
                            if (task.IsCanceled)
                            {
                                Console.WriteLine($"{nameof(DataReceiver)} - Timeout");
                                return;
                            }

                            byte[] data = task.Result;

                            if (data == null)
                            {
                                Console.WriteLine($"{nameof(DataReceiver)} - No data received");
                                await Task.Delay(100).ConfigureAwait(false);
                                return;
                            }

                            Console.WriteLine(BitConverter.ToString(data));

                        }).ConfigureAwait(false);
                    }

                }, cancellationToken).ContinueWith(task => { }).ConfigureAwait(false);
            }
            catch (Exception exception)
            {
                Console.WriteLine($"{nameof(DataReceiver)} - {exception}");
                break;
            }

            Console.WriteLine($"{nameof(DataReceiver)} - restart loop");
        }

        Console.WriteLine($"{nameof(DataReceiver)} - Stop");
    }

    private async Task<byte[]> DataReadAsync(CancellationToken cancellationToken)
    {
        byte[] buffer = new byte[100];

        Console.WriteLine($"{nameof(DataReadAsync)} - Read data...");
        var numberOfBytesToRead = await this._stream.ReadAsync(buffer, 0, buffer.Length, cancellationToken).ConfigureAwait(false);
        Console.WriteLine($"{nameof(DataReadAsync)} - NumberOfBytesToRead:{numberOfBytesToRead}");

        using (var memoryStream = new MemoryStream())
        {
            await memoryStream.WriteAsync(buffer, 0, numberOfBytesToRead, cancellationToken).ConfigureAwait(false);
            return memoryStream.ToArray();
        }
    }
}
```

**Comment by tinohager** [comment] 2022-02-20 21:52
The logic below seems to work fine for me for all .NET variants. Otherwise I would recommend to use an `#if` block so it is clear what the old code is. And can be easily removed at some point.

**Comment by jchristn** [comment] 2022-02-20 22:54
Awesome, this works perfectly @tinohager, packaging into a new release now.  Then onto the PRs you submitted.  Thanks again

**Comment by jchristn** [comment] 2022-02-20 22:55
NuGet: https://www.nuget.org/packages/SuperSimpleTcp/2.6.0.4
Commit: https://github.com/jchristn/SuperSimpleTcp/commit/1e92103d7c5051f9e4308cddd932cd6d67cad360

**Closed by jchristn** 2022-02-20 22:55 UTC
